services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
       - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend:
    build:
      context: frontend
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build:
      context: backend
      target: builder
    ports:
      - 8090:8090
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}